name: instagram_clone
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  eva_icons_flutter: ^3.1.0
  firebase_core: ^4.4.0
  shared_preferences: ^2.5.4
  firebase_auth: ^6.1.4
  fluttertoast: ^9.0.0
  cloud_firestore: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

 